#pragma once
#include "WindowsNT.hh"  // IWYU pragma: keep


constexpr char const* getErrorEnumName(DWORD code) {
    switch (code) {
    case EXCEPTION_ACCESS_VIOLATION:
        return "STATUS_ACCESS_VIOLATION";
    case EXCEPTION_DATATYPE_MISALIGNMENT:
        return "STATUS_DATATYPE_MISALIGNMENT";
    case EXCEPTION_BREAKPOINT:
        return "STATUS_BREAKPOINT";
    case EXCEPTION_SINGLE_STEP:
        return "STATUS_SINGLE_STEP";
    case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:
        return "STATUS_ARRAY_BOUNDS_EXCEEDED";
    case EXCEPTION_FLT_DENORMAL_OPERAND:
        return "STATUS_FLOAT_DENORMAL_OPERAND";
    case EXCEPTION_FLT_DIVIDE_BY_ZERO:
        return "STATUS_FLOAT_DIVIDE_BY_ZERO";
    case EXCEPTION_FLT_INEXACT_RESULT:
        return "STATUS_FLOAT_INEXACT_RESULT";
    case EXCEPTION_FLT_INVALID_OPERATION:
        return "STATUS_FLOAT_INVALID_OPERATION";
    case EXCEPTION_FLT_OVERFLOW:
        return "STATUS_FLOAT_OVERFLOW";
    case EXCEPTION_FLT_STACK_CHECK:
        return "STATUS_FLOAT_STACK_CHECK";
    case EXCEPTION_FLT_UNDERFLOW:
        return "STATUS_FLOAT_UNDERFLOW";
    case EXCEPTION_INT_DIVIDE_BY_ZERO:
        return "STATUS_INTEGER_DIVIDE_BY_ZERO";
    case EXCEPTION_INT_OVERFLOW:
        return "STATUS_INTEGER_OVERFLOW";
    case EXCEPTION_PRIV_INSTRUCTION:
        return "STATUS_PRIVILEGED_INSTRUCTION";
    case EXCEPTION_IN_PAGE_ERROR:
        return "STATUS_IN_PAGE_ERROR";
    case EXCEPTION_ILLEGAL_INSTRUCTION:
        return "STATUS_ILLEGAL_INSTRUCTION";
    case EXCEPTION_NONCONTINUABLE_EXCEPTION:
        return "STATUS_NONCONTINUABLE_EXCEPTION";
    case EXCEPTION_STACK_OVERFLOW:
        return "STATUS_STACK_OVERFLOW";
    case EXCEPTION_INVALID_DISPOSITION:
        return "STATUS_INVALID_DISPOSITION";
    case EXCEPTION_GUARD_PAGE:
        return "STATUS_GUARD_PAGE_VIOLATION";
    case EXCEPTION_INVALID_HANDLE:
        return "STATUS_INVALID_HANDLE";
    // case EXCEPTION_POSSIBLE_DEADLOCK:
    //     return "STATUS_POSSIBLE_DEADLOCK";
    case CONTROL_C_EXIT:
        return "STATUS_CONTROL_C_EXIT";
    default:
        return "unknown";
    }
}
